spring.application.name: spring-boot-config-service
my:
  greeting: Hello Magizh
list:
  of:
    numbers: One,Two,Three,Four

dbValues: "{connectionString:'test', username:'magizh', password:'magizh'}"
app:
   name: Magizh App
   description: Welcome to Magizh App

db:
  connection: "{connectionString:'test', username:'magizh', password:'magizh'}"
  host: 127.0.0.1
  port: 8080

management.endpoints.web.exposure.include: "*"

spring.cloud.config.uri: https://localhost:8888/

#Spring Profile Config
#spring.profiles.active: test